export enum CarType {
	SUV = 'SUV',
	TRUCK = 'TRUCK',
	CROSSOVER = 'CROSSOVER',
	SEDAN = 'SEDAN',
	COUPE = 'COUPE',
	CONVERTIBLE = 'CONVERTIBLE',
	LUXURY = 'LUXURY',
	SPORTS_CAR = 'SPORTS_CAR',
	MOTORCYCLE = 'MOTORCYCLE',
  }
